on:
  push:
    branches:
    - main
    - release/*

jobs:
  copr:
     runs-on: ubuntu-latest
     steps:
     - name: copr-build
  # You may pin to the exact commit or the version.
  # uses: akdev1l/copr-build@aae8c96d8cce692e8d31c6a3312989c039b983d6
       uses: akdev1l/copr-build@v1.0.2
       with:
    # COPR Project Name
           project-name: ${{ github.repository_owner }}
    # Package name in COPR
           package-name: ${{ github.event.repository.name }}
    # git remote URL
           git-remote: https://github.com/${{ github.repository_owner }}/${{ github.event.repository.name }}.git
    # COPR owner
           owner: ${{ github.repository_owner }}
    # Comittish for COPR to track
           committish:  main
              
       env:
         COPR_API_TOKEN_CONFIG: kcfpzbugnlglsgtnxrrxwohaxiuuzk
